import '../styles/index.scss'
import Footer from './components/footer';
import Header from "./components/header";
import ReduxProvider from './store/ReduxProvider';
import { Toast } from './toast';




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" 
    >
      <body>
      <ReduxProvider>
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
        <Toast />
        </ReduxProvider>
        </body>
    </html>
  );
}
